from database import db

class Organization(db.Model):
    id = db.Column(db.String, primary_key=True)
    company_name = db.Column(db.String)
    industry = db.Column(db.String)
    company_size = db.Column(db.String)
    operating_regions = db.Column(db.String)
    founded_year = db.Column(db.Integer)
    public_or_private = db.Column(db.String)
    stock_symbol = db.Column(db.String)
    vision_mission = db.Column(db.String)
    org_maturity_level = db.Column(db.String)
    hrms_integrated = db.Column(db.Boolean)
    erp_system = db.Column(db.String)
    org_chart_available = db.Column(db.Boolean)
    org_metadata_file = db.Column(db.String)

class BusinessUnit(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String)
    head = db.Column(db.String)
    email = db.Column(db.String)
    linked_departments = db.Column(db.String)
    strategic_priority = db.Column(db.String)
    kpis = db.Column(db.String)
    business_unit_type = db.Column(db.String)
    location = db.Column(db.String)
    budget_allocation = db.Column(db.Integer)

class Department(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String)
    linked_business_unit = db.Column(db.String)
    manager = db.Column(db.String)
    email = db.Column(db.String)
    headcount_budget = db.Column(db.Integer)
    function_type = db.Column(db.String)
    location = db.Column(db.String)
    shift_coverage = db.Column(db.Boolean)
    time_zone = db.Column(db.String)
    department_code = db.Column(db.String)

class RoleGroup(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    sample_roles = db.Column(db.String)
    strategic_importance = db.Column(db.String)
    business_critical = db.Column(db.Boolean)
    associated_departments = db.Column(db.String)
    role_family_code = db.Column(db.String)

class JobLevel(db.Model):
    id = db.Column(db.String, primary_key=True)
    level_name = db.Column(db.String)
    description = db.Column(db.String)
    salary_band_min = db.Column(db.Integer)
    salary_band_max = db.Column(db.Integer)
    min_experience_years = db.Column(db.Integer)
    allowed_titles = db.Column(db.String)
    level_code = db.Column(db.String)
    is_managerial = db.Column(db.Boolean)
    promotion_criteria = db.Column(db.String)

class JobSkill(db.Model):
    id = db.Column(db.String, primary_key=True)
    job_title = db.Column(db.String)
    job_level = db.Column(db.Integer)
    role_group = db.Column(db.String)
    job_family = db.Column(db.String)
    description = db.Column(db.String)
    required_skills = db.Column(db.String)
    education = db.Column(db.String)
    language_requirements = db.Column(db.String)
    reports_to = db.Column(db.String)
    work_model = db.Column(db.String)
    job_type = db.Column(db.String)
    union_affiliation = db.Column(db.Boolean)
    job_code = db.Column(db.String)
    work_location = db.Column(db.String)
    travel_required = db.Column(db.Boolean)
    compliance_requirements = db.Column(db.String)
