"""Change skill id to integer

Revision ID: bb71aab2b8e3
Revises: 9d4ebd0642fa
Create Date: 2025-06-28 01:14:24.154953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb71aab2b8e3'
down_revision = '9d4ebd0642fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('competency_skills', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('job_profile_required_skills', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('proficiency', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('skill_gap', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('skill_relationship', schema=None) as batch_op:
        batch_op.alter_column('source_skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('target_skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('skill_tag_map', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('skill_tag_map', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('skill_relationship', schema=None) as batch_op:
        batch_op.alter_column('target_skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('source_skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('skill_gap', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('proficiency', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('job_profile_required_skills', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('skill_.id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('competency_skills', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
