"""Create capability_competencies table

Revision ID: b3c92fd2e456
Revises: bb71aab2b8e3
Create Date: 2025-06-28 01:40:43.998643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b3c92fd2e456'
down_revision = 'bb71aab2b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_competencies',
    sa.Column('capability_id', sa.String(length=150), nullable=False),
    sa.Column('competency_id', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ),
    sa.PrimaryKeyConstraint('capability_id', 'competency_id')
    )
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competency_id', sa.String(length=150), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('fk_behavior_skill_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_behavior_competency_id', 'competency', ['competency_id'], ['id'])
        batch_op.drop_column('skill_id')

    with op.batch_alter_table('capability', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('competency', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('fk_competency_capability_id', type_='foreignkey')
        batch_op.drop_column('capability_id')
        batch_op.drop_column('custom_fields')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('capability_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'capability', ['capability_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('capability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_behavior_competency_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_behavior_skill_id', 'skill', ['skill_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('competency_id')

    op.drop_table('capability_competencies')
    # ### end Alembic commands ###
